#!/bin/sh

# Set these paths appropriately

BIN="/home/mariana/TREETAGGER/bin"
CMD="/home/mariana/TREETAGGER/cmd"
LIB="/home/mariana/TREETAGGER/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

