#!/bin/sh

# Set these paths appropriately

BIN="/home/mariana/TREETAGGER/bin"
CMD="/home/mariana/TREETAGGER/cmd"
LIB="/home/mariana/TREETAGGER/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
