#!/bin/sh

# Set these paths appropriately

BIN="/home/mariana/TREETAGGER/bin"
CMD="/home/mariana/TREETAGGER/cmd"
LIB="/home/mariana/TREETAGGER/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
