#!/bin/sh

# Set these paths appropriately

BIN="/home/mariana/TREETAGGER/bin"
CMD="/home/mariana/TREETAGGER/cmd"
LIB="/home/mariana/TREETAGGER/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
